# Generated by Django 6.1.1 on 2026-09-15 17:39
# Edited by hand on 2026-09-16: Event.id changed from UUIDField to an 8-char
# base62 CharField (apps.events.ids.generate_short_id) per explicit owner
# decision — see openspec/changes/add-events-api/design.md D1 (amended).
# Safe to edit this migration in place rather than adding a second one:
# this is the only migration in this app, and it has not been applied
# anywhere outside the developer's own disposable local Docker Postgres (no
# merge to develop, no deploy). Slot.id is untouched, still UUIDField.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

import apps.events.ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=apps.events.ids.generate_short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('host_nickname', models.CharField(max_length=40)),
                ('host_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mode', models.CharField(choices=[('date_only', 'Date only'), ('time_slots', 'Time slots')], max_length=20)),
                ('response_deadline', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('final_note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='final_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.slot'),
        ),
    ]
