# Generated by Django 6.1.1 on 2026-09-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mode',
            field=models.CharField(choices=[('date_only', 'Date Only'), ('time_slots', 'Time Slots')], max_length=20),
        ),
    ]
