# Generated by Django 6.1.1 on 2026-09-21 09:11

import apps.events.ids
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantResponse',
            fields=[
                ('id', models.CharField(default=apps.events.ids.generate_short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=40)),
                ('phone_last_three_hash', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantResponseAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='events.participantresponse')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantResponseSlotAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('available', 'Available'), ('if_needed', 'If Needed'), ('unavailable', 'Unavailable')], max_length=20)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_availabilities', to='events.participantresponse')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_availabilities', to='events.slot')),
            ],
            options={
                'unique_together': {('response', 'slot')},
            },
        ),
        migrations.AddField(
            model_name='participantresponse',
            name='slots',
            field=models.ManyToManyField(related_name='responses', through='events.ParticipantResponseSlotAvailability', to='events.slot'),
        ),
        migrations.AlterUniqueTogether(
            name='participantresponse',
            unique_together={('event', 'nickname')},
        ),
    ]
