# Generated by Django 6.1.1 on 2026-09-20 18:43

import apps.events.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantResponse',
            fields=[
                ('id', models.CharField(default=apps.events.ids.generate_short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=40)),
                ('phone_last_three_hash', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.event')),
                ('slots', models.ManyToManyField(related_name='responses', to='events.slot')),
            ],
            options={
                'unique_together': {('event', 'nickname')},
            },
        ),
    ]
