# Generated by Django 6.1.1 on 2026-09-21 15:24

import apps.events.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_participantresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=apps.events.ids.generate_short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.event')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
