# Generated by Django 6.1.1 on 2026-09-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_participantresponseaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantresponse',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
