# Generated by Django 6.1.1 on 2026-09-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_comment_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantresponse',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
