[project]
name = "jiu-sync-backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "celery>=5.6.3",
    "django>=6.1.1",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.14.0",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt>=5.5.1",
    "google-auth>=2.57.1",
    "gunicorn>=23.0.0",
    "psycopg[binary]>=3.3.5",
    "redis>=8.1.0",
]

[dependency-groups]
dev = [
    "django-stubs>=6.1.0",
    "factory-boy>=3.3.3",
    "pytest>=9.1.1",
    "pytest-django>=4.14.0",
    "ruff>=0.16.6",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.dev"
python_files = ["test_*.py"]
testpaths = ["apps", "tests"]

[tool.ruff]
target-version = "py313"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
