# Generated by Django 6.1.1 on 2026-09-28 07:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_participantresponse_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantRecommendationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quota_period', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('preferences', models.JSONField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, choices=[('UPSTREAM_TIMEOUT', 'Upstream Timeout'), ('UPSTREAM_HTTP_ERROR', 'Upstream Http Error'), ('UPSTREAM_INVALID_RESPONSE', 'Upstream Invalid Response'), ('NO_USABLE_RESULTS', 'No Usable Results'), ('UNEXPECTED_ERROR', 'Unexpected Error')], max_length=32, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('model', models.CharField(max_length=100)),
                ('usage', models.JSONField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_recommendations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'quota_period', 'status'], name='rec_req_user_period_status'), models.Index(fields=['user', 'event', 'status'], name='rec_req_user_event_status')],
            },
        ),
    ]
