# Generated by Django 6.1.1 on 2026-09-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_add_upstream_connection_error_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantrecommendationrequest',
            name='error_code',
            field=models.CharField(blank=True, choices=[('UPSTREAM_TIMEOUT', 'Upstream Timeout'), ('UPSTREAM_HTTP_ERROR', 'Upstream Http Error'), ('UPSTREAM_CONNECTION_ERROR', 'Upstream Connection Error'), ('UPSTREAM_INVALID_RESPONSE', 'Upstream Invalid Response'), ('NO_USABLE_RESULTS', 'No Usable Results'), ('UNEXPECTED_ERROR', 'Unexpected Error'), ('QUOTA_EXCEEDED_AT_CONFIRM', 'Quota Exceeded At Confirm')], max_length=32, null=True),
        ),
    ]
