# Generated by Django 6.1.1 on 2026-09-28 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_participantresponse_deleted_at'),
        ('recommendations', '0003_add_quota_exceeded_at_confirm_error_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRestaurantSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_ref', models.CharField(max_length=20)),
                ('restaurant', models.JSONField()),
                ('selected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_selection', to='events.event')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='recommendations.restaurantrecommendationrequest')),
            ],
        ),
    ]
